spring:
  cloud:
    gateway:
      routes:
        - id: backend
          uri: http://localhost:8081
          predicates:
            - Path=/api/patients/**
        - id: frontend
          uri: http://localhost:8082
          predicates:
            - Path=/patients/**