spring:
  cloud:
    gateway:
      routes:
        - id: backend_route
          uri: http://backend:8081  # Remplacez localhost par backend
          predicates:
            - Path=/api/patients/**  # Redirige vers le backend pour les patients
        - id: notes_route
          uri: http://backend:8081  # Remplacez localhost par backend
          predicates:
            - Path=/api/notes/**  # Redirige vers le backend pour les notes
        - id: frontend_route
          uri: http://frontend:8082  # Remplacez localhost par frontend
          predicates:
            - Path=/login  # Redirige vers la page de connexion
        - id: frontend_patients_route
          uri: http://frontend:8082  # Remplacez localhost par frontend
          predicates:
            - Path=/patients